"""Compatibility shim for :mod:`lifx.network.discovery.mdns.dns`."""

from lifx.network.discovery.mdns.dns import (
    DNS_CLASS_IN,
    DNS_CLASS_UNIQUE,
    DNS_TYPE_A,
    DNS_TYPE_AAAA,
    DNS_TYPE_PTR,
    DNS_TYPE_SRV,
    DNS_TYPE_TXT,
    DnsHeader,
    DnsResourceRecord,
    ParsedDnsResponse,
    SrvData,
    TxtData,
    build_address_query,
    build_ptr_query,
    parse_dns_response,
    parse_name,
    parse_txt_record,
)

__all__ = [
    "DNS_CLASS_IN",
    "DNS_CLASS_UNIQUE",
    "DNS_TYPE_A",
    "DNS_TYPE_AAAA",
    "DNS_TYPE_PTR",
    "DNS_TYPE_SRV",
    "DNS_TYPE_TXT",
    "DnsHeader",
    "DnsResourceRecord",
    "ParsedDnsResponse",
    "SrvData",
    "TxtData",
    "build_address_query",
    "build_ptr_query",
    "parse_dns_response",
    "parse_name",
    "parse_txt_record",
]
