"""Generated LIFX theme data.

DO NOT EDIT THIS FILE MANUALLY.
Generated from data/themes.jsonl by lifx/theme/generator.py
Regenerate with: uv run python -m lifx.theme.generator

Palette order is canonical, not captured: every palette is sorted by
its normalised (hue, saturation, brightness, kelvin) uint16 tuple,
duplicates preserved (D-24). The LIFX app shuffles palette order on
every application, so captured order is an accident, not data.

Slugs derive from the emoji-stripped display name: NFKD-normalise,
drop non-ASCII, lowercase, collapse every run of non-alphanumeric
characters to a single underscore, strip leading and trailing
underscores (D-09).
"""

from __future__ import annotations

from dataclasses import dataclass

from lifx.color import HSBK


@dataclass(frozen=True)
class ThemeRecord:
    """A generated theme: identity metadata plus canonical palette."""

    slug: str
    name: str
    category: str
    colors: tuple[HSBK, ...]


THEMES: dict[str, ThemeRecord] = {
    "cheerful": ThemeRecord(
        slug="cheerful",
        name="Cheerful",
        category="Moods",
        colors=(
            HSBK(
                hue=50.99853515625,
                saturation=1.0,
                brightness=0.6699931334401464,
                kelvin=3500,
            ),
            HSBK(
                hue=247.994384765625,
                saturation=1.0,
                brightness=0.6699931334401464,
                kelvin=3500,
            ),
            HSBK(
                hue=265.9954833984375,
                saturation=0.8699931334401465,
                brightness=0.4699931334401465,
                kelvin=3500,
            ),
            HSBK(
                hue=281.9970703125,
                saturation=1.0,
                brightness=0.6699931334401464,
                kelvin=3500,
            ),
            HSBK(hue=309.9957275390625, saturation=1.0, brightness=1.0, kelvin=3500),
        ),
    ),
    "evening": ThemeRecord(
        slug="evening",
        name="Evening",
        category="Library",
        colors=(
            HSBK(
                hue=34.002685546875,
                saturation=0.7499961852445258,
                brightness=0.9020065613794156,
                kelvin=3500,
            ),
            HSBK(
                hue=34.002685546875,
                saturation=0.8,
                brightness=0.9020065613794156,
                kelvin=3500,
            ),
            HSBK(
                hue=39.00146484375,
                saturation=0.7499961852445258,
                brightness=0.9020065613794156,
                kelvin=3500,
            ),
        ),
    ),
    "forrest": ThemeRecord(
        slug="forrest",
        name="Forrest",
        category="Nature",
        colors=(
            HSBK(hue=90.0, saturation=1.0, brightness=0.2500038147554742, kelvin=9000),
            HSBK(hue=90.0, saturation=1.0, brightness=0.5000076295109483, kelvin=9000),
            HSBK(hue=90.0, saturation=1.0, brightness=1.0, kelvin=9000),
            HSBK(
                hue=149.996337890625,
                saturation=1.0,
                brightness=0.2500038147554742,
                kelvin=9000,
            ),
            HSBK(
                hue=149.996337890625,
                saturation=1.0,
                brightness=0.5000076295109483,
                kelvin=9000,
            ),
            HSBK(hue=149.996337890625, saturation=1.0, brightness=1.0, kelvin=9000),
            HSBK(
                hue=164.9981689453125,
                saturation=1.0,
                brightness=0.2500038147554742,
                kelvin=9000,
            ),
            HSBK(
                hue=164.9981689453125,
                saturation=1.0,
                brightness=0.5000076295109483,
                kelvin=9000,
            ),
            HSBK(hue=164.9981689453125, saturation=1.0, brightness=1.0, kelvin=9000),
        ),
    ),
    "mondrian": ThemeRecord(
        slug="mondrian",
        name="Mondrian",
        category="Art Series",
        colors=(
            HSBK(hue=0.0, saturation=0.0, brightness=0.0, kelvin=6500),
            HSBK(hue=0.0, saturation=0.0, brightness=0.0, kelvin=6500),
            HSBK(hue=0.0, saturation=0.0, brightness=0.0, kelvin=6500),
            HSBK(hue=0.0, saturation=0.0, brightness=0.0, kelvin=6500),
            HSBK(hue=0.0, saturation=0.0, brightness=0.0, kelvin=6500),
            HSBK(hue=0.0, saturation=0.0, brightness=0.0, kelvin=6500),
            HSBK(hue=0.0, saturation=0.0, brightness=1.0, kelvin=6500),
            HSBK(hue=0.0, saturation=0.0, brightness=1.0, kelvin=6500),
            HSBK(hue=0.0, saturation=1.0, brightness=1.0, kelvin=3500),
            HSBK(hue=0.0, saturation=1.0, brightness=1.0, kelvin=3500),
            HSBK(hue=0.0, saturation=1.0, brightness=1.0, kelvin=3500),
            HSBK(hue=60.0018310546875, saturation=1.0, brightness=1.0, kelvin=3500),
            HSBK(hue=239.996337890625, saturation=1.0, brightness=1.0, kelvin=3500),
            HSBK(hue=239.996337890625, saturation=1.0, brightness=1.0, kelvin=3500),
            HSBK(hue=239.996337890625, saturation=1.0, brightness=1.0, kelvin=3500),
            HSBK(hue=239.996337890625, saturation=1.0, brightness=1.0, kelvin=3500),
        ),
    ),
}

# Rename aliases: each alias key binds the target's own
# record, so the alias carries the target's identity
# (D-13, D-14).
THEMES["forest"] = THEMES["forrest"]
